"""empty message

Revision ID: 244530653311
Revises: 7197b12237a2
Create Date: 2019-03-27 15:00:56.640489

"""

# revision identifiers, used by Alembic.
revision = '244530653311'
down_revision = '7197b12237a2'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.add_column('pack', sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('pack', 'category')

    # ### end Alembic commands ###
