"""empty message

Revision ID: 86445de2c2c9
Revises: 679d8593c1b2
Create Date: 2018-11-13 16:34:15.285401

"""

# revision identifiers, used by Alembic.
revision = '86445de2c2c9'
down_revision = '679d8593c1b2'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phish_tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phish_id', sa.String(), nullable=False),
    sa.Column('verified', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('online', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phish_tank_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_log_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=False),
    sa.Column('phish_tank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phish_tank_id'], ['phish_tank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_table('phish_tank_detections')
    op.drop_table('phish_tank')
    # ### end Alembic commands ###
