"""empty message

Revision ID: 88ded24e39c7
Revises: 8fbff117e23d
Create Date: 2018-10-18 14:35:17.654122

"""

# revision identifiers, used by Alembic.
revision = '88ded24e39c7'
down_revision = '8fbff117e23d'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('dashboard_data')
    # ### end Alembic commands ###
