"""empty message

Revision ID: 8fbff117e23d
Revises: 51fe1cb8479e
Create Date: 2018-10-09 18:40:13.920475

"""

# revision identifiers, used by Alembic.
revision = '8fbff117e23d'
down_revision = '51fe1cb8479e'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virus_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('response', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('detections', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('avs', sa.String(), nullable=True),
    sa.Column('cves', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('virus_total')
    # ### end Alembic commands ###
