"""empty message

Revision ID: f04a79a898c2
Revises: 233d98c00d66
Create Date: 2019-01-23 12:44:21.551451

"""

# revision identifiers, used by Alembic.
revision = 'f04a79a898c2'
down_revision = '233d98c00d66'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=True))

    op.add_column('rule', sa.Column('severity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('rule', 'severity')

    op.drop_column('alerts', 'severity')


    # ### end Alembic commands ###
