"""empty message

Revision ID: 5706960fcdb4
Revises: 86445de2c2c9
Create Date: 2018-12-26 11:23:37.790315

"""

# revision identifiers, used by Alembic.
revision = '5706960fcdb4'
down_revision = '86445de2c2c9'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('node', sa.Column('apply_recon', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('node', 'apply_recon')

    # ### end Alembic commands ###
