"""empty message

Revision ID: 658de397b180
Revises: cfba03d1e0e6
Create Date: 2019-06-11 11:08:25.168161

"""

# revision identifiers, used by Alembic.
revision = '658de397b180'
down_revision = 'cfba03d1e0e6'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filters', postgresql.JSONB(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('apply_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sql', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('shard', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_query')
    op.drop_table('default_filters')
    # ### end Alembic commands ###
