"""empty message

Revision ID: 02095e5181bd
Revises: cf177f7d6eff
Create Date: 2020-07-28 20:31:34.455940

"""

# revision identifiers, used by Alembic.
revision = '02095e5181bd'
down_revision = 'cf177f7d6eff'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('state', sa.Integer(), nullable=True))
    op.execute("UPDATE node set state = 0")
    op.add_column('node', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'state')
    op.drop_column('node', 'updated_at')
    # ### end Alembic commands ###
