"""empty message

Revision ID: 097a3ca3d31c
Revises: 53d372cb535a
Create Date: 2019-10-04 11:32:37.261454

"""

# revision identifiers, used by Alembic.
revision = '097a3ca3d31c'
down_revision = '4fc26be903e3'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_query', sa.Column('snapshot', sa.Boolean(), nullable=True))
    op.add_column('query', sa.Column('snapshot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'snapshot')
    op.drop_column('default_query', 'snapshot')
    # ### end Alembic commands ###
