"""empty message

Revision ID: 27ac66cfa860
Revises: a79cb013f1ad
Create Date: 2020-09-30 19:05:35.480004

"""

# revision identifiers, used by Alembic.
revision = '27ac66cfa860'
down_revision = 'a79cb013f1ad'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('result_log_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_log_name', 'alert_log', ['name'], unique=False)
    op.create_index('idx_alert_log_result_log_uuid', 'alert_log', ['result_log_uuid'], unique=False)
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_created_at_desc', 'alerts', ['created_at', sa.text('created_at DESC')], unique=False)
    op.execute("""CREATE or REPLACE FUNCTION node_query_count() RETURNS trigger
       LANGUAGE plpgsql AS
    $$BEGIN
       IF TG_OP = 'INSERT' and NEW.action != 'removed' THEN
       
          UPDATE node_query_count SET total_results = total_results + 1 where node_id=NEW.node_id and query_name=NEW.name;

           IF found THEN
                RETURN NEW;
           END IF;
           BEGIN
                INSERT INTO  node_query_count(total_results,node_id,query_name) VALUES (1,NEW.node_id, NEW.name);
                RETURN NEW;
           END;
           
       ELSIF TG_OP = 'DELETE' and OLD.action != 'removed' THEN

          UPDATE node_query_count SET total_results = total_results - 1 where node_id=OLD.node_id and query_name=OLD.name;
          DELETE from node_query_count where total_results=0;
          RETURN OLD;
          
       ELSE
       
          RETURN NULL;
          
       END IF;
    END;$$;
     """)
    op.execute("DELETE FROM node_query_count;")
    op.execute("""
     INSERT INTO node_query_count(total_results,node_id,query_name)
    SELECT count(*),node_id,name FROM result_log group by name,node_id;
     """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_alerts_created_at_desc', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_index('idx_alert_log_result_log_uuid', table_name='alert_log')
    op.drop_index('idx_alert_log_name', table_name='alert_log')
    op.drop_table('alert_log')

    # ### end Alembic commands ###
