"""empty message

Revision ID: 2ff330668729
Revises: 3568d23c6249
Create Date: 2020-11-02 17:36:24.671935

"""

# revision identifiers, used by Alembic.
revision = '2ff330668729'
down_revision = '3568d23c6249'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE INDEX idx_result_log_on_columns_target_path ON result_log  USING BTREE((columns->> 'target_path'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_target_name ON result_log  USING BTREE((columns->> 'target_name'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_process_name ON result_log  USING BTREE((columns->> 'process_name'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_remote_address ON result_log  USING BTREE((columns->> 'remote_address'));")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_result_log_on_columns_target_path', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_target_name', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_process_name', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_remote_address', table_name='result_log')

    # ### end Alembic commands ###
