"""empty message

Revision ID: 352f4b476585
Revises: e85b0d231ebc
Create Date: 2020-05-20 18:39:07.577847

"""

# revision identifiers, used by Alembic.
revision = '352f4b476585'
down_revision = '4b6de2085d8c'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_result_log_name', 'result_log', ['name'], unique=False)
    op.drop_index('index_node_recon_data_on_columns', table_name='node_recon_data')
    op.drop_index('index_node_recon_data_on_columns_path', table_name='node_recon_data')

    op.execute("CREATE INDEX idx_result_log_on_columns_parent_process_guid ON result_log  USING BTREE((columns->> 'parent_process_guid'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_process_guid ON result_log  USING BTREE((columns->> 'process_guid'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_time ON result_log  USING BTREE((columns->> 'time'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_md5 ON result_log  USING BTREE((columns->> 'md5'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_sha256 ON result_log  USING BTREE((columns->> 'sha256'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_domain_name ON result_log  USING BTREE((columns->> 'domain_name'));")
    op.execute("CREATE INDEX idx_result_log_on_columns_ja3_md5 ON result_log  USING BTREE((columns->> 'ja3_md5'));")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_result_log_on_columns_time', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_process_guid', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_md5', table_name='result_log')
    op.drop_index('idx_result_log_name', table_name='result_log')
    op.drop_index('idx_result_log_on_columns_parent_process_guid', table_name='result_log')

    # ### end Alembic commands ###
