"""empty message

Revision ID: 3568d23c6249
Revises: c426eedfc474
Create Date: 2020-10-21 21:42:40.764950

"""

# revision identifiers, used by Alembic.
revision = '3568d23c6249'
down_revision = 'c426eedfc474'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virus_total_av_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virus_total_av_engines')
    # ### end Alembic commands ###
