"""empty message

Revision ID: 4fc26be903e3
Revises: 53d372cb535a
Create Date: 2019-10-19 14:44:18.880829

"""

# revision identifiers, used by Alembic.
revision = '4fc26be903e3'
down_revision = '53d372cb535a'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('result_log', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('result_log', sa.Column('task_id', sa.String(), nullable=True))
    op.rename_table('manual_threat_intel', 'ioc_intel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('result_log', 'status')

    # ### end Alembic commands ###
