"""empty message

Revision ID: 679d8593c1b2
Revises: 8fbff117e23d
Create Date: 2018-10-30 21:03:33.915000

"""

# revision identifiers, used by Alembic.
revision = '679d8593c1b2'
down_revision = '88ded24e39c7'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibm_force_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('malware_family', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('risk', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('ibm_force_exchange')
    # ### end Alembic commands ###
