"""empty message

Revision ID: 7197b12237a2
Revises: 680ca326fb32
Create Date: 2019-03-18 16:32:32.059598

"""

# revision identifiers, used by Alembic.
revision = '7197b12237a2'
down_revision = '680ca326fb32'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intel_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intel_name', sa.String(), nullable=True),
    sa.Column('credentials', postgresql.JSONB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('threat_intel_credentials')
    # ### end Alembic commands ###
