"""empty message

Revision ID: a79cb013f1ad
Revises: d88775b11256
Create Date: 2020-08-31 10:39:49.367269

"""

# revision identifiers, used by Alembic.
revision = 'a79cb013f1ad'
down_revision = 'd88775b11256'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_email', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alert_email', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('alert_email_node_id_fkey', 'alert_email', type_='foreignkey')
    op.drop_constraint('alert_email_alert_id_fkey', 'alert_email', type_='foreignkey')
    op.create_foreign_key(None, 'alert_email', 'node', ['node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'alert_email', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.alter_column('carve_session', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('carve_session_node_id_fkey', 'carve_session', type_='foreignkey')
    op.create_foreign_key(None, 'carve_session', 'node', ['node_id'], ['id'], ondelete='CASCADE')
    op.alter_column('distributed_query_task', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('distributed_query_task_node_id_fkey', 'distributed_query_task', type_='foreignkey')
    op.create_foreign_key(None, 'distributed_query_task', 'node', ['node_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distributed_query_task', type_='foreignkey')
    op.create_foreign_key('distributed_query_task_node_id_fkey', 'distributed_query_task', 'node', ['node_id'], ['id'])
    op.alter_column('distributed_query_task', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_constraint(None, 'carve_session', type_='foreignkey')
    op.create_foreign_key('carve_session_node_id_fkey', 'carve_session', 'node', ['node_id'], ['id'])
    op.alter_column('carve_session', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'alert_email', type_='foreignkey')
    op.drop_constraint(None, 'alert_email', type_='foreignkey')
    op.create_foreign_key('alert_email_alert_id_fkey', 'alert_email', 'alerts', ['alert_id'], ['id'])
    op.create_foreign_key('alert_email_node_id_fkey', 'alert_email', 'node', ['node_id'], ['id'])
    op.alter_column('alert_email', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('alert_email', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
