"""empty message

Revision ID: d88775b11256
Revises: a0a63da840f7
Create Date: 2020-08-25 22:13:46.903586

"""

# revision identifiers, used by Alembic.
revision = 'd88775b11256'
down_revision = 'a0a63da840f7'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('released_agent_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_release', sa.String(), nullable=True),
    sa.Column('osquery_version', sa.String(), nullable=True),
    sa.Column('extension_version', sa.String(), nullable=True),
    sa.Column('extension_hash_md5', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('default_query', 'config_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('released_agent_versions')
    # ### end Alembic commands ###
