"""empty message

Revision ID: f7a19a90adfd
Revises: 47386cd00c1e
Create Date: 2019-11-19 12:22:36.090021

"""

# revision identifiers, used by Alembic.
revision = 'j8emsbzxcq1k'
down_revision = 'f7a19a90adfd'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("UPDATE default_query SET arch = 'x86_64' where arch is null;")
    op.execute("UPDATE default_filters SET arch = 'x86_64' where arch is null;")
    op.execute("UPDATE result_log SET task_id = '-1' where task_id is null;")

    op.alter_column('default_query', 'arch', nullable=False)
    op.alter_column('default_filters', 'arch', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    pass
