"""empty message

Revision ID: cf177f7d6eff
Revises: 352f4b476585
Create Date: 2020-07-16 15:51:51.367615

"""

# revision identifiers, used by Alembic.
revision = 'cf177f7d6eff'
down_revision = '352f4b476585'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'node', 'is_active',
                    server_default='0');


    op.execute("UPDATE node SET is_active = false ;")
    # ### end Alembic commands ###


def downgrade():
    op.alter_column(u'node', 'is_active',
                    server_default='1');


    # ### commands auto generated by Alembic - please adjust! ###
