"""empty message

Revision ID: 47386cd00c1e
Revises: 097a3ca3d31c
Create Date: 2019-11-04 15:38:50.094123

"""

# revision identifiers, used by Alembic.
revision = '47386cd00c1e'
down_revision = '097a3ca3d31c'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carved_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('carve_session', sa.Column('completed_blocks', sa.Integer(), nullable=True))
    op.add_column('carve_session', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('carve_session', sa.Column('status', sa.String(), nullable=True))
    op.add_column('carve_session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('carve_session', 'blocks_received')

    op.add_column('node', sa.Column('host_details', postgresql.JSONB(), nullable=True))

    op.drop_column('node', 'apply_recon')
    op.drop_column('node', 'last_results_seen_date')
    op.drop_column('node', 'config_id')
    op.drop_column('node', 'last_results_update_date')

    op.add_column('node',sa.Column('last_status', sa.DateTime(), nullable=True)),
    op.add_column('node',sa.Column('last_result', sa.DateTime(), nullable=True)),
    op.add_column('node',sa.Column('last_config', sa.DateTime(), nullable=True)),
    op.add_column('node',sa.Column('last_query_read', sa.DateTime(), nullable=True)),
    op.add_column('node',sa.Column('last_query_write', sa.DateTime(), nullable=True)),
    op.drop_table('phish_tank_detections')
    op.drop_table('alert_distributed_query')

    op.alter_column(u'alerts', 'rule_id',
                    nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('node', sa.Column('last_results_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('last_results_seen_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('apply_recon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('node', 'host_details')

    op.add_column('carve_session', sa.Column('blocks_received', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.drop_column('carve_session', 'updated_at')
    op.drop_column('carve_session', 'status')
    op.drop_column('carve_session', 'request_id')
    op.drop_column('carve_session', 'completed_blocks')

    op.drop_table('carved_block')

    op.drop_column('node', 'last_status')
    op.drop_column('node', 'last_result')
    op.drop_column('node', 'last_config')
    op.drop_column('node', 'last_query_read')
    op.drop_column('node', 'last_query_write')

    op.create_table('phish_tank_detections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result_log_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(), autoincrement=False, nullable=False),
    sa.Column('phish_tank_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phish_tank_id'], ['phish_tank.id'], name='phish_tank_detections_phish_tank_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phish_tank_detections_pkey')
    )

    op.create_table('alert_distributed_query',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('alert_id', sa.String(), nullable=False),
                    sa.Column('distributed_query_id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
