"""empty message

Revision ID: 680ca326fb32
Revises: 584896579af6
Create Date: 2019-02-21 16:53:23.882145

"""

# revision identifiers, used by Alembic.
revision = '680ca326fb32'
down_revision = '584896579af6'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('alerts', sa.Column('result_log_uid', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('source', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('source_data', postgresql.JSONB(), nullable=True))
    op.add_column('alerts', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('alerts', 'result_log_id')
    op.drop_column('alerts', 'sql')
    op.add_column('result_log', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('alerts', 'sql')

