"""empty message

Revision ID: fcf6cc75ebd2
Revises: 698f286777f0
Create Date: 2018-09-24 15:17:42.788226

"""

# revision identifiers, used by Alembic.
revision = 'fcf6cc75ebd2'
down_revision = '698f286777f0'

from alembic import op
import sqlalchemy as sa
import polylogyx.database
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_config', sa.Column('platform', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():

    op.drop_column('node_config', 'platform')

