"""empty message

Revision ID: cfba03d1e0e6
Revises:
Create Date: 2019-05-03 10:55:19.473023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfba03d1e0e6'
down_revision = '244530653311'



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handling_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(), nullable=False),
    sa.Column('token_expired', sa.Boolean(), nullable=False),
    sa.Column('logged_out_at', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('handling_token')
    # ### end Alembic commands ###
